export const GET_PROFILE_REQUEST = "GET_PROFILE_REQUEST";
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";
export const GET_PROFILE_FAILURE = "GET_PROFILE_FAILURE";

export const GET_PROFILE_BY_USERID_REQUEST = "GET_PROFILE_BY_USERID_REQUEST";
export const GET_PROFILE_BY_USERID_SUCCESS = "GET_PROFILE_BY_USERID_SUCCESS";
export const GET_PROFILE_BY_USERID_FAILURE = "GET_PROFILE_BY_USERID_FAILURE";

export const UPDATE_PROFILE_REQUEST = "UPDATE_PROFILE_REQUEST";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_FAILURE = "UPDATE_PROFILE_FAILURE";

export const SET_DEFAULT_ADDRESS_REQUEST = "SET_DEFAULT_ADDRESS_REQUEST";
export const SET_DEFAULT_ADDRESS_SUCCESS = "SET_DEFAULT_ADDRESS_SUCCESS";
export const SET_DEFAULT_ADDRESS_FAILURE = "SET_DEFAULT_ADDRESS_FAILURE";

export const CLEAR_PROFILE_ERROR = "CLEAR_PROFILE_ERROR";